[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
x402_insurance = "DMahL9qujZiirzLXKFvJxHhsNxG9uXh1yi1EnUCYgH7w"

[programs.devnet]
x402_insurance = "DMahL9qujZiirzLXKFvJxHhsNxG9uXh1yi1EnUCYgH7w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
